/**
 * GitHub 仓库管理服务
 * 用于自动创建仓库、推送模板文件、更新内容
 */

const GITHUB_API_BASE = 'https://api.github.com';

interface GitHubRepoConfig {
  token: string;
  owner: string;
  repoName: string;
  description?: string;
  isPrivate?: boolean;
}

interface GitHubFile {
  path: string;
  content: string;
}

interface GitHubCommitResult {
  sha: string;
  url: string;
}

/**
 * 创建 GitHub 仓库
 */
export async function createGitHubRepo(config: GitHubRepoConfig): Promise<{
  success: boolean;
  repoUrl?: string;
  error?: string;
}> {
  try {
    const response = await fetch(`${GITHUB_API_BASE}/user/repos`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${config.token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: config.repoName,
        description: config.description || 'Auto-generated by NicheDigger PSEO',
        private: config.isPrivate || false,
        auto_init: true, // 创建初始 README
        has_issues: false,
        has_projects: false,
        has_wiki: false,
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      // 如果仓库已存在，返回成功
      if (response.status === 422 && error.errors?.[0]?.message?.includes('already exists')) {
        return {
          success: true,
          repoUrl: `https://github.com/${config.owner}/${config.repoName}`,
        };
      }
      return {
        success: false,
        error: error.message || `GitHub API error: ${response.status}`,
      };
    }

    const data = await response.json();
    return {
      success: true,
      repoUrl: data.html_url,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message || 'Failed to create GitHub repo',
    };
  }
}

/**
 * 检查仓库是否存在
 */
export async function checkRepoExists(config: {
  token: string;
  owner: string;
  repoName: string;
}): Promise<boolean> {
  try {
    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${config.owner}/${config.repoName}`,
      {
        headers: {
          'Authorization': `Bearer ${config.token}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      }
    );
    return response.ok;
  } catch {
    return false;
  }
}

/**
 * 获取文件的 SHA（用于更新）
 */
async function getFileSha(config: {
  token: string;
  owner: string;
  repoName: string;
  path: string;
  branch?: string;
}): Promise<string | null> {
  try {
    const url = `${GITHUB_API_BASE}/repos/${config.owner}/${config.repoName}/contents/${config.path}?ref=${config.branch || 'main'}`;
    console.log(`[GitHub getFileSha] Checking file: ${config.path}`);
    console.log(`[GitHub getFileSha] URL: ${url}`);

    const response = await fetch(
      url,
      {
        headers: {
          'Authorization': `Bearer ${config.token}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      }
    );

    console.log(`[GitHub getFileSha] Response status: ${response.status}`);

    if (!response.ok) {
      if (response.status === 404) {
        console.log(`[GitHub getFileSha] File not found (404) - will create new file`);
      } else {
        const errorData = await response.json().catch(() => ({}));
        console.log(`[GitHub getFileSha] Error response:`, errorData);
      }
      return null;
    }

    const data = await response.json();
    console.log(`[GitHub getFileSha] Found existing file with SHA: ${data.sha}`);
    return data.sha;
  } catch (error: any) {
    console.error(`[GitHub getFileSha] Exception:`, error.message);
    return null;
  }
}

/**
 * 创建或更新单个文件
 */
export async function createOrUpdateFile(config: {
  token: string;
  owner: string;
  repoName: string;
  path: string;
  content: string;
  message: string;
  branch?: string;
}): Promise<{ success: boolean; sha?: string; error?: string }> {
  try {
    console.log(`[GitHub] Creating/updating file: ${config.path}`);
    console.log(`[GitHub] Repository: ${config.owner}/${config.repoName}`);
    console.log(`[GitHub] Branch: ${config.branch || 'main'}`);
    console.log(`[GitHub] Content length: ${config.content?.length || 0} characters`);

    // 验证内容不为空
    if (!config.content || config.content.trim().length === 0) {
      console.error(`[GitHub] ❌ Content is empty for file: ${config.path}`);
      return {
        success: false,
        error: 'File content is empty. Cannot push empty file to GitHub.',
      };
    }

    // 获取现有文件的 SHA（如果存在）
    const existingSha = await getFileSha({
      token: config.token,
      owner: config.owner,
      repoName: config.repoName,
      path: config.path,
      branch: config.branch,
    });

    if (existingSha) {
      console.log(`[GitHub] File exists, updating with SHA: ${existingSha}`);
    } else {
      console.log(`[GitHub] File does not exist, creating new file`);
    }

    const body: any = {
      message: config.message,
      content: Buffer.from(config.content).toString('base64'),
      branch: config.branch || 'main',
    };

    if (existingSha) {
      body.sha = existingSha;
    }

    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${config.owner}/${config.repoName}/contents/${config.path}`,
      {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${config.token}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      }
    );

    if (!response.ok) {
      const error = await response.json();
      console.error(`[GitHub] ❌ API error: ${response.status}`, error);
      return {
        success: false,
        error: error.message || `GitHub API error: ${response.status}`,
      };
    }

    const data = await response.json();
    console.log(`[GitHub] ✅ File pushed successfully: ${data.content?.html_url || config.path}`);
    return {
      success: true,
      sha: data.content?.sha,
    };
  } catch (error: any) {
    console.error(`[GitHub] ❌ Exception:`, error);
    return {
      success: false,
      error: error.message || 'Failed to create/update file',
    };
  }
}

/**
 * 批量创建文件（通过多次 API 调用）
 */
export async function createMultipleFiles(config: {
  token: string;
  owner: string;
  repoName: string;
  files: GitHubFile[];
  message: string;
  branch?: string;
}): Promise<{ success: boolean; errors?: string[] }> {
  const errors: string[] = [];

  for (const file of config.files) {
    const result = await createOrUpdateFile({
      token: config.token,
      owner: config.owner,
      repoName: config.repoName,
      path: file.path,
      content: file.content,
      message: config.message,
      branch: config.branch,
    });

    if (!result.success) {
      errors.push(`${file.path}: ${result.error}`);
    }

    // 短暂延迟避免 rate limiting
    await new Promise(resolve => setTimeout(resolve, 100));
  }

  return {
    success: errors.length === 0,
    errors: errors.length > 0 ? errors : undefined,
  };
}

/**
 * 生成 MkDocs 模板文件
 */
export function generateMkDocsTemplate(config: {
  siteName: string;
  siteUrl: string;
  siteDescription: string;
  repoOwner: string;
  repoName: string;
}): GitHubFile[] {
  const mkdocsYml = `# MkDocs 配置 - NicheDigger PSEO
site_name: "${config.siteName}"
site_url: "${config.siteUrl}"
site_description: "${config.siteDescription}"

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.sections
    - search.suggest
    - toc.integrate

repo_url: https://github.com/${config.repoOwner}/${config.repoName}
repo_name: ${config.repoOwner}/${config.repoName}

docs_dir: docs
use_directory_urls: true

nav:
  - Home: index.md
# 新文章将在此处自动添加

markdown_extensions:
  - tables
  - toc:
      permalink: true
`;

  const indexMd = `# ${config.siteName}

${config.siteDescription}

## Welcome

This site contains high-quality, SEO-optimized content covering various topics. Browse the navigation menu to explore our articles.

## Categories

- **Guides**: Comprehensive guides and tutorials
- **Comparisons**: In-depth product and service comparisons
- **Tools**: Useful tools and resources
- **Lab**: Experimental content and research

---

*This site is powered by [MkDocs](https://www.mkdocs.org/) and automatically updated.*
`;

  const requirementsTxt = `mkdocs>=1.5
mkdocs-material>=9.0
`;

  const readthedocsYaml = `version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
`;

  return [
    { path: 'mkdocs.yml', content: mkdocsYml },
    { path: 'docs/index.md', content: indexMd },
    { path: 'requirements.txt', content: requirementsTxt },
    { path: '.readthedocs.yaml', content: readthedocsYaml },
  ];
}

/**
 * 初始化 MkDocs 仓库
 * 创建仓库并推送模板文件
 */
export async function initializeMkDocsRepo(config: {
  token: string;
  owner: string;
  repoName: string;
  siteName: string;
  siteUrl: string;
  siteDescription: string;
}): Promise<{
  success: boolean;
  repoUrl?: string;
  error?: string;
}> {
  // 1. 创建仓库
  const createResult = await createGitHubRepo({
    token: config.token,
    owner: config.owner,
    repoName: config.repoName,
    description: config.siteDescription,
    isPrivate: false,
  });

  if (!createResult.success) {
    return createResult;
  }

  // 等待仓库初始化完成
  await new Promise(resolve => setTimeout(resolve, 2000));

  // 2. 生成模板文件
  const files = generateMkDocsTemplate({
    siteName: config.siteName,
    siteUrl: config.siteUrl,
    siteDescription: config.siteDescription,
    repoOwner: config.owner,
    repoName: config.repoName,
  });

  // 3. 推送模板文件
  const pushResult = await createMultipleFiles({
    token: config.token,
    owner: config.owner,
    repoName: config.repoName,
    files,
    message: 'Initial MkDocs setup by NicheDigger PSEO',
    branch: 'main',
  });

  if (!pushResult.success) {
    return {
      success: false,
      error: `Failed to push template files: ${pushResult.errors?.join(', ')}`,
    };
  }

  return {
    success: true,
    repoUrl: createResult.repoUrl,
  };
}

/**
 * 添加文章到 MkDocs 仓库
 */
export async function addArticleToMkDocs(config: {
  token: string;
  owner: string;
  repoName: string;
  articleSlug: string;
  articleTitle: string;
  articleContent: string;
  branch?: string;
  extension?: string;
  isUpdate?: boolean; // 新增：标识是否为更新操作
}): Promise<{
  success: boolean;
  articlePath?: string;
  error?: string;
}> {
  const ext = config.extension || '.md';
  const articlePath = `docs/${config.articleSlug}${ext}`;

  console.log(`[GitHub addArticleToMkDocs] Article path: ${articlePath}`);
  console.log(`[GitHub addArticleToMkDocs] Is update: ${config.isUpdate || false}`);

  // 添加文章内容
  const result = await createOrUpdateFile({
    token: config.token,
    owner: config.owner,
    repoName: config.repoName,
    path: articlePath,
    content: config.articleContent,
    message: config.isUpdate
      ? `Update article: ${config.articleTitle}`
      : `Add article: ${config.articleTitle}`,
    branch: config.branch,
  });

  if (!result.success) {
    return {
      success: false,
      error: result.error,
    };
  }

  // 只有 Markdown 文件才添加到 MkDocs 导航
  if (ext === '.md') {
    // 更新 mkdocs.yml 的 nav 部分
    await updateMkDocsNav({
      token: config.token,
      owner: config.owner,
      repoName: config.repoName,
      articleSlug: config.articleSlug,
      articleTitle: config.articleTitle,
      branch: config.branch,
    });
  }

  return {
    success: true,
    articlePath,
  };
}

/**
 * 更新 mkdocs.yml 的 nav 部分
 * 支持按类别组织文章（lab, guide, compare, tool）
 */
async function updateMkDocsNav(config: {
  token: string;
  owner: string;
  repoName: string;
  articleSlug: string;
  articleTitle: string;
  branch?: string;
}): Promise<void> {
  try {
    console.log(`[GitHub updateMkDocsNav] Updating navigation for: ${config.articleTitle}`);

    // 获取当前 mkdocs.yml
    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${config.owner}/${config.repoName}/contents/mkdocs.yml?ref=${config.branch || 'main'}`,
      {
        headers: {
          'Authorization': `Bearer ${config.token}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      }
    );

    if (!response.ok) {
      console.warn(`[GitHub updateMkDocsNav] Could not fetch mkdocs.yml: ${response.status}`);
      return;
    }

    const data = await response.json();
    const currentContent = Buffer.from(data.content, 'base64').toString('utf-8');

    // 检查文章是否已在 nav 中
    if (currentContent.includes(`${config.articleSlug}.md`)) {
      console.log(`[GitHub updateMkDocsNav] Article already in navigation, skipping`);
      return; // 已存在
    }

    // 确定文章类别（从 slug 中提取，如果有前缀的话）
    let category = 'Articles'; // 默认类别
    let displaySlug = config.articleSlug;

    // 检测常见的 fast/slow knife 路径前缀
    if (config.articleSlug.startsWith('lab/') || config.articleSlug.startsWith('test/')) {
      category = 'Lab (Experimental)';
    } else if (config.articleSlug.startsWith('guide/')) {
      category = 'Guides';
    } else if (config.articleSlug.startsWith('compare/')) {
      category = 'Comparisons';
    } else if (config.articleSlug.startsWith('tool/')) {
      category = 'Tools';
    }

    // 构建导航条目
    const navEntry = `    - "${config.articleTitle}": ${config.articleSlug}.md`;

    let updatedContent = currentContent;

    // 查找或创建类别部分
    const categoryPattern = new RegExp(`  - ${category}:\\s*\\n`, 'i');
    const hasCategory = categoryPattern.test(currentContent);

    if (hasCategory) {
      // 在现有类别下添加
      updatedContent = currentContent.replace(
        categoryPattern,
        `  - ${category}:\n${navEntry}\n`
      );
      console.log(`[GitHub updateMkDocsNav] Added to existing category: ${category}`);
    } else {
      // 创建新类别（在标记之前添加）
      const marker = '# 新文章将在此处自动添加';
      if (currentContent.includes(marker)) {
        const newCategory = `  - ${category}:\n${navEntry}\n${marker}`;
        updatedContent = currentContent.replace(marker, newCategory);
        console.log(`[GitHub updateMkDocsNav] Created new category: ${category}`);
      } else {
        // 如果没有标记，在 nav 部分末尾添加
        const navEndPattern = /\nmarkdown_extensions:/;
        if (navEndPattern.test(currentContent)) {
          updatedContent = currentContent.replace(
            navEndPattern,
            `\n  - ${category}:\n${navEntry}\n\nmarkdown_extensions:`
          );
        } else {
          // 最后的备选方案：直接追加到文件末尾
          updatedContent = currentContent.trimEnd() + `\n  - ${category}:\n${navEntry}\n`;
        }
        console.log(`[GitHub updateMkDocsNav] Added new category at end: ${category}`);
      }
    }

    // 更新文件
    const updateResult = await createOrUpdateFile({
      token: config.token,
      owner: config.owner,
      repoName: config.repoName,
      path: 'mkdocs.yml',
      content: updatedContent,
      message: `Add "${config.articleTitle}" to navigation`,
      branch: config.branch,
    });

    if (updateResult.success) {
      console.log(`[GitHub updateMkDocsNav] ✅ Navigation updated successfully`);
    } else {
      console.error(`[GitHub updateMkDocsNav] ❌ Failed to update navigation: ${updateResult.error}`);
    }
  } catch (error: any) {
    console.error('[GitHub updateMkDocsNav] Error:', error.message);
  }
}

/**
 * 列出仓库内容
 */
export async function listRepoContents(config: {
  token: string;
  owner: string;
  repoName: string;
  path?: string;
  branch?: string;
}): Promise<{ success: boolean; files?: any[]; error?: string }> {
  try {
    const path = config.path || '';
    console.log(`[GitHub] Listing contents: ${config.owner}/${config.repoName}/${path || '(root)'}`);

    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${config.owner}/${config.repoName}/contents/${path}?ref=${config.branch || 'main'}`,
      {
        headers: {
          'Authorization': `Bearer ${config.token}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      }
    );

    if (!response.ok) {
      const error = await response.json();
      console.error(`[GitHub] ❌ Failed to list contents: ${response.status}`, error);
      return {
        success: false,
        error: error.message || `GitHub API error: ${response.status}`,
      };
    }

    const data = await response.json();
    console.log(`[GitHub] ✅ Found ${Array.isArray(data) ? data.length : 1} items`);
    return {
      success: true,
      files: Array.isArray(data) ? data : [data],
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message || 'Failed to list repo contents',
    };
  }
}
