/**
 * GitHub 仓库管理服务
 * 用于自动创建仓库、推送模板文件、更新内容
 */

const GITHUB_API_BASE = 'https://api.github.com';

interface GitHubRepoConfig {
  token: string;
  owner: string;
  repoName: string;
  description?: string;
  isPrivate?: boolean;
}

interface GitHubFile {
  path: string;
  content: string;
}

interface GitHubCommitResult {
  sha: string;
  url: string;
}

/**
 * 创建 GitHub 仓库
 */
export async function createGitHubRepo(config: GitHubRepoConfig): Promise<{
  success: boolean;
  repoUrl?: string;
  error?: string;
}> {
  try {
    const response = await fetch(`${GITHUB_API_BASE}/user/repos`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${config.token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: config.repoName,
        description: config.description || 'Auto-generated by NicheDigger PSEO',
        private: config.isPrivate || false,
        auto_init: true, // 创建初始 README
        has_issues: false,
        has_projects: false,
        has_wiki: false,
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      // 如果仓库已存在，返回成功
      if (response.status === 422 && error.errors?.[0]?.message?.includes('already exists')) {
        return {
          success: true,
          repoUrl: `https://github.com/${config.owner}/${config.repoName}`,
        };
      }
      return {
        success: false,
        error: error.message || `GitHub API error: ${response.status}`,
      };
    }

    const data = await response.json();
    return {
      success: true,
      repoUrl: data.html_url,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message || 'Failed to create GitHub repo',
    };
  }
}

/**
 * 检查仓库是否存在
 */
export async function checkRepoExists(config: {
  token: string;
  owner: string;
  repoName: string;
}): Promise<boolean> {
  try {
    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${config.owner}/${config.repoName}`,
      {
        headers: {
          'Authorization': `Bearer ${config.token}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      }
    );
    return response.ok;
  } catch {
    return false;
  }
}

/**
 * 获取文件的 SHA（用于更新）
 */
async function getFileSha(config: {
  token: string;
  owner: string;
  repoName: string;
  path: string;
  branch?: string;
}): Promise<string | null> {
  try {
    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${config.owner}/${config.repoName}/contents/${config.path}?ref=${config.branch || 'main'}`,
      {
        headers: {
          'Authorization': `Bearer ${config.token}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      }
    );
    
    if (!response.ok) return null;
    const data = await response.json();
    return data.sha;
  } catch {
    return null;
  }
}

/**
 * 创建或更新单个文件
 */
export async function createOrUpdateFile(config: {
  token: string;
  owner: string;
  repoName: string;
  path: string;
  content: string;
  message: string;
  branch?: string;
}): Promise<{ success: boolean; sha?: string; error?: string }> {
  try {
    // 获取现有文件的 SHA（如果存在）
    const existingSha = await getFileSha({
      token: config.token,
      owner: config.owner,
      repoName: config.repoName,
      path: config.path,
      branch: config.branch,
    });

    const body: any = {
      message: config.message,
      content: Buffer.from(config.content).toString('base64'),
      branch: config.branch || 'main',
    };

    if (existingSha) {
      body.sha = existingSha;
    }

    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${config.owner}/${config.repoName}/contents/${config.path}`,
      {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${config.token}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      }
    );

    if (!response.ok) {
      const error = await response.json();
      return {
        success: false,
        error: error.message || `GitHub API error: ${response.status}`,
      };
    }

    const data = await response.json();
    return {
      success: true,
      sha: data.content?.sha,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message || 'Failed to create/update file',
    };
  }
}

/**
 * 批量创建文件（通过多次 API 调用）
 */
export async function createMultipleFiles(config: {
  token: string;
  owner: string;
  repoName: string;
  files: GitHubFile[];
  message: string;
  branch?: string;
}): Promise<{ success: boolean; errors?: string[] }> {
  const errors: string[] = [];
  
  for (const file of config.files) {
    const result = await createOrUpdateFile({
      token: config.token,
      owner: config.owner,
      repoName: config.repoName,
      path: file.path,
      content: file.content,
      message: config.message,
      branch: config.branch,
    });
    
    if (!result.success) {
      errors.push(`${file.path}: ${result.error}`);
    }
    
    // 短暂延迟避免 rate limiting
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  
  return {
    success: errors.length === 0,
    errors: errors.length > 0 ? errors : undefined,
  };
}

/**
 * 生成 MkDocs 模板文件
 */
export function generateMkDocsTemplate(config: {
  siteName: string;
  siteUrl: string;
  siteDescription: string;
  repoOwner: string;
  repoName: string;
}): GitHubFile[] {
  const mkdocsYml = `# MkDocs 配置 - NicheDigger PSEO
site_name: "${config.siteName}"
site_url: "${config.siteUrl}"
site_description: "${config.siteDescription}"

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.sections
    - search.suggest
    - toc.integrate

repo_url: https://github.com/${config.repoOwner}/${config.repoName}
repo_name: ${config.repoOwner}/${config.repoName}

docs_dir: docs
use_directory_urls: true

nav:
  - Home: index.md
# 新文章将在此处自动添加

markdown_extensions:
  - tables
  - toc:
      permalink: true
`;

  const indexMd = `# Welcome to ${config.siteName}

${config.siteDescription}

---

*Content will be added automatically.*
`;

  const requirementsTxt = `mkdocs>=1.5
mkdocs-material>=9.0
`;

  const readthedocsYaml = `version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
`;

  return [
    { path: 'mkdocs.yml', content: mkdocsYml },
    { path: 'docs/index.md', content: indexMd },
    { path: 'requirements.txt', content: requirementsTxt },
    { path: '.readthedocs.yaml', content: readthedocsYaml },
  ];
}

/**
 * 初始化 MkDocs 仓库
 * 创建仓库并推送模板文件
 */
export async function initializeMkDocsRepo(config: {
  token: string;
  owner: string;
  repoName: string;
  siteName: string;
  siteUrl: string;
  siteDescription: string;
}): Promise<{
  success: boolean;
  repoUrl?: string;
  error?: string;
}> {
  // 1. 创建仓库
  const createResult = await createGitHubRepo({
    token: config.token,
    owner: config.owner,
    repoName: config.repoName,
    description: config.siteDescription,
    isPrivate: false,
  });

  if (!createResult.success) {
    return createResult;
  }

  // 等待仓库初始化完成
  await new Promise(resolve => setTimeout(resolve, 2000));

  // 2. 生成模板文件
  const files = generateMkDocsTemplate({
    siteName: config.siteName,
    siteUrl: config.siteUrl,
    siteDescription: config.siteDescription,
    repoOwner: config.owner,
    repoName: config.repoName,
  });

  // 3. 推送模板文件
  const pushResult = await createMultipleFiles({
    token: config.token,
    owner: config.owner,
    repoName: config.repoName,
    files,
    message: 'Initial MkDocs setup by NicheDigger PSEO',
    branch: 'main',
  });

  if (!pushResult.success) {
    return {
      success: false,
      error: `Failed to push template files: ${pushResult.errors?.join(', ')}`,
    };
  }

  return {
    success: true,
    repoUrl: createResult.repoUrl,
  };
}

/**
 * 添加文章到 MkDocs 仓库
 */
export async function addArticleToMkDocs(config: {
  token: string;
  owner: string;
  repoName: string;
  articleSlug: string;
  articleTitle: string;
  articleContent: string;
  branch?: string;
}): Promise<{
  success: boolean;
  articlePath?: string;
  error?: string;
}> {
  const articlePath = `docs/${config.articleSlug}.md`;
  
  // 添加文章内容
  const result = await createOrUpdateFile({
    token: config.token,
    owner: config.owner,
    repoName: config.repoName,
    path: articlePath,
    content: config.articleContent,
    message: `Add article: ${config.articleTitle}`,
    branch: config.branch,
  });

  if (!result.success) {
    return {
      success: false,
      error: result.error,
    };
  }

  // 更新 mkdocs.yml 的 nav 部分
  await updateMkDocsNav({
    token: config.token,
    owner: config.owner,
    repoName: config.repoName,
    articleSlug: config.articleSlug,
    articleTitle: config.articleTitle,
    branch: config.branch,
  });

  return {
    success: true,
    articlePath,
  };
}

/**
 * 更新 mkdocs.yml 的 nav 部分
 */
async function updateMkDocsNav(config: {
  token: string;
  owner: string;
  repoName: string;
  articleSlug: string;
  articleTitle: string;
  branch?: string;
}): Promise<void> {
  try {
    // 获取当前 mkdocs.yml
    const response = await fetch(
      `${GITHUB_API_BASE}/repos/${config.owner}/${config.repoName}/contents/mkdocs.yml?ref=${config.branch || 'main'}`,
      {
        headers: {
          'Authorization': `Bearer ${config.token}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      }
    );

    if (!response.ok) return;

    const data = await response.json();
    const currentContent = Buffer.from(data.content, 'base64').toString('utf-8');
    
    // 检查文章是否已在 nav 中
    const navEntry = `  - "${config.articleTitle}": ${config.articleSlug}.md`;
    if (currentContent.includes(config.articleSlug)) {
      return; // 已存在
    }

    // 在 nav 末尾添加新文章（在 "# 新文章将在此处自动添加" 之前）
    let updatedContent = currentContent;
    const marker = '# 新文章将在此处自动添加';
    if (currentContent.includes(marker)) {
      updatedContent = currentContent.replace(
        marker,
        `${navEntry}\n${marker}`
      );
    } else {
      // 如果没有标记，在 nav 部分末尾添加
      updatedContent = currentContent.trimEnd() + `\n${navEntry}\n`;
    }

    // 更新文件
    await createOrUpdateFile({
      token: config.token,
      owner: config.owner,
      repoName: config.repoName,
      path: 'mkdocs.yml',
      content: updatedContent,
      message: `Add "${config.articleTitle}" to navigation`,
      branch: config.branch,
    });
  } catch (error) {
    console.error('[updateMkDocsNav] Error:', error);
  }
}
